server {
    listen 80;
    server_name sttgo.francecentral.cloudapp.azure.com localhost;

    # Rediriger tout le trafic HTTP vers HTTPS
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name sttgo.francecentral.cloudapp.azure.com localhost;

    ssl_certificate /etc/letsencrypt/live/sttgo.francecentral.cloudapp.azure.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/sttgo.francecentral.cloudapp.azure.com/privkey.pem;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Redirection des appels API vers le conteneur backend
    location /api/ {
        proxy_pass http://sttgo-backend:8889/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Optimisation pour les fichiers statiques (images, js, css)
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public";
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
