server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        # Cette ligne est la clé : elle redirige tout vers index.html si le chemin n'est pas un fichier réel
        try_files $uri $uri/ /index.html;
    }

    # Optimisation pour les fichiers statiques (images, js, css)
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public";
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
