persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log
listener 1883

# Securite : authentification obligatoire par mot de passe
allow_anonymous false
password_file /mosquitto/config/passwd
