services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sttgo_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto-broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  backend:
    build: ./sttgo-backend
    container_name: sttgo-backend
    ports:
      - "8889:8889"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/sttgo_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - MQTT_BROKER_URL=tcp://mosquitto:1883
    depends_on:
      mysql-db:
        condition: service_healthy
      mosquitto:
        condition: service_started

  frontend:
    build: ./sttgo-frontend
    container_name: sttgo-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mysql_data:
