services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    restart: always

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto-broker
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: always

  backend:
    build: ./sttgo-backend
    container_name: sttgo-backend
    ports:
      - "8889:8889"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/${DB_NAME}?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=${DB_ROOT_PASSWORD}
      - MQTT_BROKER_URL=tcp://mosquitto:1883
      - APP_FRONTEND_URL=https://sttgo.francecentral.cloudapp.azure.com
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    depends_on:
      mysql-db:
        condition: service_healthy
      mosquitto:
        condition: service_started

  frontend:
    build: ./sttgo-frontend
    container_name: sttgo-frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend
    restart: always

volumes:
  mysql_data:
